import { supabase } from '../../db/supabaseClient';
import { Tour, TourStep, TourWithSteps, TourAnalytics} from './../../types/tour';

/**
 * Fetch all tours with their steps
 */
export async function getAllTours(): Promise<TourWithSteps[]> {
  const { data: tours, error: toursError } = await supabase
    .from('tours')
    .select('*')
    .order('created_at', { ascending: false })

  if (toursError) throw toursError

  // Fetch steps for each tour
  const toursWithSteps = await Promise.all(
    (tours || []).map(async (tour) => {
      const { data: steps, error: stepsError } = await supabase
        .from('tour_steps')
        .select('*')
        .eq('tour_id', tour.id)
        .order('order', { ascending: true }) // Changed from step_number to order

      if (stepsError) throw stepsError

      return {
        ...tour,
        steps: steps || [],
      }
    })
  )

  return toursWithSteps
}

/**
 * Fetch a single tour by ID with its steps
 */
export async function getTourById(tourId: string): Promise<TourWithSteps | null> {
  const { data: tour, error: tourError } = await supabase
    .from('tours')
    .select('*')
    .eq('id', tourId)
    .single()

  if (tourError) throw tourError
  if (!tour) return null

  const { data: steps, error: stepsError } = await supabase
    .from('tour_steps')
    .select('*')
    .eq('tour_id', tourId)
    .order('order', { ascending: true }) // Changed from step_number to order

  if (stepsError) throw stepsError

  return {
    ...tour,
    steps: steps || [],
  }
}

/**
 * Create a new tour
 * Note: embed_key is auto-generated by the database
 */
export async function createTour(
  tour: Omit<Tour, 'id' | 'created_at' | 'updated_at' | 'embed_key'>
): Promise<Tour> {
  const { data, error } = await supabase
    .from('tours')
    .insert([tour])
    .select()
    .single()

  if (error) throw error
  return data
}

/**
 * Update an existing tour
 */
export async function updateTour(
  tourId: string,
  updates: Partial<Omit<Tour, 'id' | 'created_at' | 'updated_at' | 'embed_key' | 'user_id'>>
): Promise<Tour> {
  const { data, error } = await supabase
    .from('tours')
    .update(updates)
    .eq('id', tourId)
    .select()
    .single()

  if (error) throw error
  return data
}

/**
 * Delete a tour (cascades to steps automatically)
 */
export async function deleteTour(tourId: string): Promise<void> {
  const { error } = await supabase.from('tours').delete().eq('id', tourId)

  if (error) throw error
}

/**
 * Add a step to a tour
 */
export async function addTourStep(
  step: Omit<TourStep, 'id' | 'created_at'>
): Promise<TourStep> {
  const { data, error } = await supabase
    .from('tour_steps')
    .insert([step])
    .select()
    .single()

  if (error) throw error
  return data
}

/**
 * Update a tour step
 */
export async function updateTourStep(
  stepId: string,
  updates: Partial<Omit<TourStep, 'id' | 'tour_id' | 'created_at' | 'step_id'>>
): Promise<TourStep> {
  const { data, error } = await supabase
    .from('tour_steps')
    .update(updates)
    .eq('id', stepId)
    .select()
    .single()

  if (error) throw error
  return data
}

/**
 * Delete a tour step
 */
export async function deleteTourStep(stepId: string): Promise<void> {
  const { error } = await supabase.from('tour_steps').delete().eq('id', stepId)

  if (error) throw error
}

/**
 * Track user tour progress
 */
export async function trackTourProgress(
  tourId: string,
  userId: string,
  stepsCompleted: number,
  completed: boolean = false
): Promise<TourAnalytics> {
  const analyticsData = {
    tour_id: tourId,
    user_id: userId,
    steps_completed: stepsCompleted,
    completed,
    started_at: new Date().toISOString(),
    ...(completed && { completed_at: new Date().toISOString() }),
  }

  // Check if record exists
  const { data: existing } = await supabase
    .from('tour_analytics')
    .select('id')
    .eq('tour_id', tourId)
    .eq('user_id', userId)
    .single()

  if (existing) {
    const { data, error } = await supabase
      .from('tour_analytics')
      .update(analyticsData)
      .eq('id', existing.id)
      .select()
      .single()

    if (error) throw error
    return data
  } else {
    const { data, error } = await supabase
      .from('tour_analytics')
      .insert([analyticsData])
      .select()
      .single()

    if (error) throw error
    return data
  }
}

/**
 * Get tour analytics for a specific tour
 */
export async function getTourAnalytics(tourId: string): Promise<TourAnalytics[]> {
  const { data, error } = await supabase
    .from('tour_analytics')
    .select('*')
    .eq('tour_id', tourId)

  if (error) throw error
  return data || []
}